# Generated by Django 3.2.6 on 2025-07-21 09:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã môn học')),
                ('credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Số tín chỉ')),
                ('subject_type', models.CharField(choices=[('general', 'Chung'), ('major', 'Chuyên ngành'), ('elective', 'Tự chọn')], default='general', max_length=20, verbose_name='Loại môn học')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả môn học')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='prerequisite_subjects', to='myapp.Subject', verbose_name='Điều kiện tiên quyết')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL, verbose_name='Giảng viên phụ trách')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề tài liệu')),
                ('url', models.URLField(verbose_name='URL tài liệu')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tài liệu')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='myapp.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Tài liệu tham khảo',
                'verbose_name_plural': 'Tài liệu tham khảo',
                'ordering': ['subject', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài học')),
                ('lesson_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số thứ tự bài học')),
                ('lesson_type', models.CharField(choices=[('theory', 'Lý thuyết'), ('practice', 'Thực hành'), ('project', 'Dự án')], default='theory', max_length=20, verbose_name='Loại bài học')),
                ('content', models.TextField(verbose_name='Nội dung bài học')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL video bài học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='myapp.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'ordering': ['subject', 'lesson_number'],
                'unique_together': {('subject', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài tập')),
                ('description', models.TextField(verbose_name='Mô tả bài tập')),
                ('due_date', models.DateTimeField(verbose_name='Hạn nộp bài tập')),
                ('assignment_type', models.CharField(choices=[('homework', 'Bài tập về nhà'), ('project', 'Dự án'), ('quiz', 'Bài kiểm tra')], default='homework', max_length=20, verbose_name='Loại bài tập')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='myapp.lesson', verbose_name='Bài học')),
            ],
            options={
                'verbose_name': 'Bài tập',
                'verbose_name_plural': 'Bài tập',
                'ordering': ['lesson', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian nộp')),
                ('content', models.TextField(verbose_name='Nội dung nộp bài')),
                ('grade', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Điểm số')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='myapp.assignment', verbose_name='Bài tập')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Bài nộp',
                'verbose_name_plural': 'Bài nộp',
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
