# Generated by Django 3.2.6 on 2025-07-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_assignment_lesson_reference_subject_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
