# Generated by Django 3.2.6 on 2025-07-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Mã môn học'),
        ),
    ]
